### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by linusheck** [galatolofederico/manim-presentation#11]
Hi, I'm pretty sure that manim_presentation has a "memory leak" with regards to `cv2`. It doesn't unload the non-playing videos? I definitely keeps them in RAM. So it's not really a leak, but if your presentation is in sum bigger than your RAM, you have a problem.

**Comment by linusheck** [comment]
I can look at it and fix it soon :) I definitely will need to fix it until my presentation :D

**Comment by linusheck** [comment]
See my PR :) #12

**Comment by galatolofederico** [comment]
Thanks for the fix!
