### ISSUE TITLE
Arrow keys not responding - MacBook Pro, German keyboard

### ISSUE THREAD

**Issue by PhotonSpheres** [galatolofederico/manim-presentation#13]
When starting a presentation, the arrow keys on my MacBook Pro - Catalina 10.15.6 - 2019 - German Keyboard - are not responding. Spacebar, `q` and `r` are working just fine.

I have no idea how to figure out what code my arrow keys have, hence the issue here.

**Comment by galatolofederico** [comment]
A lot of users have problems with the keybindings, give me 10 minutes and i will add a configuration wizard tool!

**Comment by galatolofederico** [comment]
Solved in version `0.2.1` with 87bbc9a8c6ea86330fb31ab0391c5bc066c63660 
You should update the package with `pip install -U manim-presentation` and then you should be able to run `manim-presentation-wizard`. Follow the steps of the wizard and it will generate a configuration file according to your needs!
