### ISSUE TITLE
Fullscreen not really fullscreen

### ISSUE THREAD

**Issue by linusheck** [galatolofederico/manim-presentation#6]
And another one: One fullscreen, there's still a small border around the window. This causes weird aliasing effects. Will see if I can fix this as well.

**Comment by emonhossainraihan** [comment]
@glatteis, Did you solve it? I am also facing problems when recording my slideshow. Is there any way to resize the window for a higher resolution scene?

**Comment by linusheck** [comment]
Hi, I have a fork https://github.com/glatteis/manim-presentation where the fullscreen works with the --fullscreen flag. But this fork has a few different issues, see https://github.com/galatolofederico/manim-presentation/pull/7. I will be working on my presentation and fix the fork when I have time :)

**Comment by linusheck** [comment]
If you want to use only the fullscreen and not the rest of my fork, this is the only thing you need to change: https://github.com/galatolofederico/manim-presentation/pull/7/commits/41de20567564ade96bd243e24477dcbc5602b0f0

**Comment by emonhossainraihan** [comment]
I have one question, @glatteis. I install manim_presentation using virtualenv, like

```
>>>virtualenv --python=python3.7 env
>>>source env/bin/activate
(env)>>>pip install manim manim-presentation opencv-python
```

Now I want to modify the following code as [41de205](https://github.com/galatolofederico/manim-presentation/commit/41de20567564ade96bd243e24477dcbc5602b0f0). But when I try to find the module path,

```
(env)>>>whereis manim_presentation
manim_presentation: /home/emonhossain/Desktop/manim-presentation/env/bin/manim_presentation
```

But that file contains only. 

```py
# -*- coding: utf-8 -*-
import re
import sys
from manim_presentation.present import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
I am not super familiar with python. Could you help me with how I can modify the `present.py` file?

<hr>

I have opened another [issue](https://github.com/galatolofederico/manim-presentation/issues/8). Let me know if you have some idea about that, please.

**Comment by linusheck** [comment]
Hi, yeah dependencies are always a pain. You should do it like this: In your virtualenv, uninstall manim-presentation with pip. Then clone my branch, and in its main folder type `pip install .`. Then it should have the correct version.

**Comment by galatolofederico** [comment]
#7 has been merged but it guess this issue remains open, am i right?

**Comment by linusheck** [comment]
Try the --fullscreen flag :)
