### ISSUE TITLE
Is there anyway to control the manim_presentation window size?

### ISSUE THREAD

**Issue by emonhossainraihan** [galatolofederico/manim-presentation#8]
## Description

manim_presentation works nicely with small size `(-ql).` 

![Screenshot from 2021-06-08 20-14-50](https://user-images.githubusercontent.com/34622219/121201427-56b0a980-c896-11eb-9b9b-701fd3f66954.png)

But soon, the rendering creates a problem with larger size `(-qh)` and `(-qk).`  Because some content is not showing for the `-qk` file due to large size. This also happens with `-qh` for the bottom area.

![Screenshot from 2021-06-08 20-11-41](https://user-images.githubusercontent.com/34622219/121200717-c4a8a100-c895-11eb-8fc6-9851431f1fe1.png)

It will be greater if we have some controlling/resizing system. I have found how to adjust resolution,

```py
import cv2

cap = cv2.VideoCapture(0)

def make_1080p():
    cap.set(3, 1920)
    cap.set(4, 1080)

def make_720p():
    cap.set(3, 1280)
    cap.set(4, 720)
```

But couldn't manage where to set `cap.set(*,*)` inside `present.py.`

## Expecting feature

- Have some controlling/resizing system

**Comment by galatolofederico** [comment]
Thanks for the issue! i will be back on this problem. I guess that i simple downscale/upscale with opencv should do the trick
