### ISSUE TITLE
Play animation in reverse when pressing back key

### ISSUE THREAD

**Issue by leleogere** [galatolofederico/manim-presentation#9]
When I press the back key, the player jumps to the previous pause in the code. It would be nice to have an option which allow to play the video in reverse to that previous pause.
I had a quick look on the internet, but it does not seems to be trivial to do it with cv2. I suggest it anyway in case of you are in search of new features to implement one day!
Good job tho it works like a charm, thanks for your tool!
(I do not know how to put this as an enhancement instead of an issue ^^)

**Comment by galatolofederico** [comment]
Thanks! yeah i don't like it either that the animation starts over again and a rewind would be so much nicer. 
The next weeks i am super busy with other projects but as soon as i will have some spare time i will give it a try!
